export interface User {
  uid: string;
  email?: string;
  role: 'admin' | 'teacher' | 'parent';
  name?: string;
  createdAt: Date;
}

export interface Student {
  id: string;
  name: string;
  age: number;
  class: string;
  rollNumber: string;
  parentPhone?: string;
  parentEmail?: string;
  photoUrl?: string;
  qrCode?: string; // QR code URL/data - only generated by admin
  registeredBy: 'admin' | 'teacher';
  registeredByUid: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Attendance {
  id: string;
  studentId: string;
  date: string; // YYYY-MM-DD format
  status: 'present' | 'absent' | 'late';
  markedBy: string; // teacher uid
  markedAt: Date;
}

export interface Grade {
  id: string;
  studentId: string;
  subject: string;
  score: number;
  maxScore: number;
  examType: 'quiz' | 'test' | 'assignment' | 'final';
  date: Date;
  teacherUid: string;
}

export interface Class {
  id: string;
  name: string;
  grade: string;
  teacherUid: string;
  studentIds: string[];
  subjects: string[];
}

export interface QRStudentCard {
  studentId: string;
  generateUrl: string; // URL to the student ID card page
  createdAt: Date;
  createdBy: string; // admin uid
}