export interface User {
  uid: string;
  email?: string;
  role: 'admin' | 'teacher' | 'parent' | 'student';
  name?: string;
  studentId?: string; // for student role mapping to student document
  createdAt: Date;
}

export interface Student {
  id: string;
  // Unified display name (preferred)
  name: string;
  // Legacy separate fields (optional)
  firstName?: string;
  lastName?: string;
  // Unified class label
  class: string;
  // Legacy class level (optional)
  classLevel?: string;
  // Student's own email for authentication (added for student login capability)
  email?: string;
  age: number;
  rollNumber: string;
  parentPhone?: string;
  parentEmail?: string;
  photoUrl?: string;
  qrCode?: string; // QR code URL/data - only generated by admin
  qrGeneratedAt?: Date;
  qrGeneratedBy?: string;
  qrHistory?: { generatedAt: Date; generatedBy: string }[];
  registeredBy: 'admin' | 'teacher';
  registeredByUid: string;
  feeStatus?: { term1:boolean; term2:boolean; term3:boolean };
  createdAt: Date;
  updatedAt: Date;
}

export interface Attendance {
  id: string;
  studentId: string;
  date: string; // YYYY-MM-DD format
  status: 'present' | 'absent' | 'late';
  markedBy: string; // teacher uid
  markedAt: Date;
}

export interface Grade {
  id: string;
  studentId: string;
  subject: string;
  score: number;
  maxScore: number;
  examType: 'quiz' | 'test' | 'assignment' | 'final';
  date: Date;
  teacherUid: string;
}

export interface Class {
  id: string;
  name: string;
  grade: string;
  teacherUid: string;
  studentIds: string[];
  subjects: string[];
}

export interface QRStudentCard {
  studentId: string;
  generateUrl: string; // URL to the student ID card page
  createdAt: Date;
  createdBy: string; // admin uid
}